GET http://localhost:3000/register

###
POST http://localhost:3000/register

Content-Type:application/json

{
  "username": "adam_richard",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}

###

POST http://localhost:3000/login

Content-Type: application/json

{
    "name":"uma123",
    "password":"uma@123"
}
###

PUT http://localhost:3000/change-password

Content-Type: application/json

{
    "username": "uma123",
    "oldPassword": "uma@123",
    "newPassword": "uma@567"
}